remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "contrast"

# Site Settings
locale                   : "Ko-KR"
title                    : ""
title_separator          : "-"
name                     : "Woogear Kwon"
description              : # "Morning Lover"
url                      : https://woogearkwon.github.io
#baseurl                  : ""
repository               : WoogearKwon/woogearkwon.github.io
github                   : [metadata]
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # "/assets/images/logo.png"
words_per_minute         : 200
comments:
  provider               : "utterances"
  utterances:
    theme                : "github-light"
    issue_term           : "pathname"
    label                : "comment"
search                   : true, false (default)
search_full_content      : true, false (default)
search_provider          : google
lunr:
  search_within_pages    : # true, false (default)
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Woogear Kwon"
  avatar           : "/assets/images/profile-woogear.png"
  bio              : ""
  location         : # "Seoul, South Korea"
  email            : # "woogear.kwon@gmail.com"
  links:
    - label: "woogear.kwon@gmail.com"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:woogear.kwon@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/WoogearKwon"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/woogear-kwon-a964a1153/"

# Site Footer
#footer:
#  links:
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      # url:
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/WoogearKwon"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      # url:
#    - label: "email"
#      icon: "fas fa-fw fa-envelope-square"
#      # url: "mailto:woogear.kwon@gmail.com"
#    - label: "linkedin"
#      icon: "fas fa-fw fa-linkedin"
#      # url: "https://www.linkedin.com/in/woogear-kwon-a964a1153/"


# Reading Files
include:
  - .htaccess
  - _pages
  - _layouts
  - _data
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: false